name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift.org"
      # https://github.com/swiftlang/swift-syntax/issues/2986
      api_breakage_check_enabled: false
      # https://github.com/swiftlang/swift-syntax/issues/2987
      docs_check_enabled: false
      # https://github.com/swiftlang/swift-syntax/issues/2988
      format_check_enabled: false
      # https://github.com/swiftlang/swift-syntax/issues/2989
      license_header_check_enabled: false
      # https://github.com/swiftlang/swift-syntax/issues/2990
      unacceptable_language_check_enabled: false
      # https://github.com/swiftlang/swift-syntax/issues/2991
      yamllint_check_enabled: false
